local module = {
    library = {
        ["A Rock"] = {
            Accel = 0.05;
            BackwardsEfficiency = 3;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "It's not just a boulder...";
            Icon = "rbxassetid://71668336719720";
            Level = 1;
            MaxSpeed = 50000;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.2;
            Unpurchasable = true
        };
        Airboat = {
            Accel = 0.75;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "";
            Icon = "rbxassetid://118034141225193";
            Level = 1000;
            MaxSpeed = 210;
            Price = 5000000;
            StopEfficiency = 1.75;
            TurningSpeed = 0.8;
            Untradeable = true
        };
        ["Ancient Megalodon"] = {
            Accel = 0.1;
            BackwardsEfficiency = 1;
            Bobbing = 6;
            BobbingSpeed = 3;
            Description = "A little dangerous...";
            Icon = "rbxassetid://105722349951484";
            Level = 1;
            MaxSpeed = 230;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.4;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Angler's Raft"] = {
            Accel = 0.32;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "[Angler Exclusive Reward]";
            Icon = "rbxassetid://137035588547889";
            Level = 1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 3.5;
            TurningSpeed = 0.7;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Aquarium Boat"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "I have an aquarium!";
            HideInShop = true;
            Icon = "rbxassetid://93687303900702";
            Level = 1;
            MaxSpeed = 150;
            Price = 20000;
            StopEfficiency = 1.5;
            TurningSpeed = 0.54;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Archaeological Boat"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 1;
            BobbingSpeed = 3;
            Description = "Boat used by archaeologists from ancient island.";
            Icon = "rbxassetid://82626003313983";
            Level = 30;
            MaxSpeed = 80;
            Price = 20000;
            StopEfficiency = 2;
            TurningSpeed = 0.3;
            Unpurchasable = true
        };
        ["Arctic Explorer"] = {
            Accel = 0.25;
            AlternateSpawn = 30;
            BackwardsEfficiency = 1.1;
            Bobbing = 1.5;
            BobbingSpeed = 1.5;
            Description = "LEGO Arctic Explorer Ship";
            Icon = "rbxassetid://106886543519092";
            Level = 1;
            MaxSpeed = 100;
            Price = -1;
            StopEfficiency = 2.2;
            TurningSpeed = 0.33;
            Unpurchasable = true
        };
        ["Atlantean Jetski"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "The Atlantean Jet Ski is a glowing, rune-etched watercraft powered by a silent crystal engine, blending speed and elegance.";
            ExpirationDate = "1738422000000";
            Icon = "rbxassetid://92057714698349";
            Level = 1;
            LimitedAmount = 15000;
            MaxSpeed = 210;
            Price = -1;
            ProductId = 2706853697;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Atlantean Pontoon"] = {
            Accel = 0.4;
            BackwardsEfficiency = 1;
            Bobbing = 1;
            BobbingSpeed = 1;
            Description = "Great for parties with some atlantean buddies!";
            Icon = "rbxassetid://129307569555429";
            Level = 1;
            MaxSpeed = 160;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.4;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Atlantean Quacker"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 4;
            BobbingSpeed = 0.5;
            Description = "ATLANTEAN DUCK!";
            Icon = "rbxassetid://80676589364492";
            Level = -1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Axofloatie = {
            Accel = 1.13;
            BackwardsEfficiency = 1.1;
            Bobbing = 0.5;
            BobbingSpeed = 0.1;
            Description = "";
            Icon = "rbxassetid://85867502998281";
            Level = 1;
            MaxSpeed = 235;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 0.65;
            Unpurchasable = true
        };
        ["Banana Cruiser"] = {
            Accel = 1.1;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "Splash into the ocean with our Banana Cruiser! An aerodynamic, tropical watercraft designed to capture the sweet Summer season.";
            Icon = "rbxassetid://125038563008473";
            Level = 1;
            MaxSpeed = 240;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Bass Boat"] = {
            Accel = 0.22;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Great for fishing with pals!";
            Icon = "rbxassetid://82321210811947";
            Level = 10;
            MaxSpeed = 45;
            Price = 6000;
            StopEfficiency = 0.7;
            TurningSpeed = 0.4
        };
        ["Black Comet"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Streak across the waves like a falling star; the Black Comet leaves only darkness in its wake...";
            FakePrice = 3899;
            Icon = "rbxassetid://79864326273860";
            Level = 1;
            LimitedAmount = 1250;
            MaxSpeed = 270;
            Price = -1;
            ProductId = 3355198363;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Block = {
            Accel = 0.1;
            BackwardsEfficiency = 1;
            Bobbing = 0;
            BobbingSpeed = 1;
            Description = "First modelling job... did I do good?";
            Icon = "rbxassetid://112614833835250";
            Level = 1;
            MaxSpeed = math.huge;
            Price = -1;
            StopEfficiency = 100;
            TurningSpeed = 50;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Bloop Boat"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "???";
            Icon = "rbxassetid://111447839171751";
            Level = 1;
            MaxSpeed = 225;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Blue Cat"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Experience smooth sailing in style with the Blue Cat, a medium sized luxury boat purring with elegance.";
            Icon = "rbxassetid://76479620423317";
            Level = 1;
            MaxSpeed = 235;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 0.7;
            Unpurchasable = true
        };
        Brick = {
            Accel = 0.01;
            BackwardsEfficiency = 1;
            Bobbing = 0;
            BobbingSpeed = 0;
            Description = "🧱";
            Icon = "rbxassetid://111526498434575";
            Level = 1;
            MaxSpeed = 1000;
            Price = -1;
            StopEfficiency = 20;
            TurningSpeed = 1;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Bunny Jetski"] = {
            Accel = 0.9;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Unstoppable Easter joy!";
            Icon = "rbxassetid://137056616134430";
            Level = 1;
            MaxSpeed = 245;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Camera Boat"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.25;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Lights, camera, action!";
            Icon = "rbxassetid://98664846868494";
            Level = 1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Candy Crawlie"] = {
            Accel = 1.55;
            BackwardsEfficiency = 1.1;
            Bobbing = 0;
            BobbingSpeed = 0.1;
            Description = "so cuddly.. so sweet.. so creepy!";
            Icon = "rbxassetid://111567114319071";
            Level = 1;
            MaxSpeed = 250;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Captain's Goldfish"] = {
            Accel = 1;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "A gleaming boat lovingly modeled after the captain's own pet goldfish, blending nautical charm with a splash of personality.";
            Icon = "rbxassetid://87054703495104";
            Level = 1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Cardboard Box"] = {
            Accel = 1.2;
            BackwardsEfficiency = 1.5;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "Isn't it gonna get wet?";
            Icon = "rbxassetid://125730231392097";
            Level = 1;
            MaxSpeed = 165;
            Price = -1;
            StopEfficiency = 2.5;
            TurningSpeed = 0.5;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Carrot Hopper"] = {
            Accel = 1;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "A playful carrot bunny born from the lush rows of the Carrot Garden!";
            Icon = "rbxassetid://115518713139810";
            Level = 1;
            MaxSpeed = 240;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Celestial Cruiser"] = {
            Accel = 0.4;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "A high-tech cruiser infused with celestial energy.";
            ExpirationDate = "1737212400000";
            Icon = "rbxassetid://139280064840536";
            Level = 1;
            LimitedAmount = 10000;
            MaxSpeed = 230;
            Price = -1;
            ProductId = 2689989326;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        Chair = {
            Accel = 0.5;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "🪑 - only for da cool people.";
            Icon = "rbxassetid://115979227935769";
            Level = 1;
            MaxSpeed = 185;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 1.5;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Chromatic Titan"] = {
            Accel = 1;
            BackwardsEfficiency = 1.5;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "Huh? Who wouldn't want this!";
            Icon = "rbxassetid://81429515459671";
            Level = 1;
            MaxSpeed = 145;
            Price = -1;
            StopEfficiency = 2.5;
            TurningSpeed = 0.5;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Classic Pumpkin"] = {
            Accel = 0.1;
            BackwardsEfficiency = 3;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Halloween Spotlight Reward [Rune Tier]";
            Icon = "rbxassetid://81301566351186";
            Level = 1;
            MaxSpeed = 100;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.2;
            Unpurchasable = true
        };
        Clawberus = {
            Accel = 0.35;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "A monstrous triple clawed lobster vessel forged from myth and salt, built to drag legends to the surface.";
            Icon = "rbxassetid://87636758084219";
            Level = 1;
            MaxSpeed = 180;
            Price = -1;
            StopEfficiency = 1.8;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Cobalt Corsair"] = {
            Accel = 0.7;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Sleek and stormborn, it cuts through waves like a blade of blue steel.";
            Icon = "rbxassetid://99027746232066";
            Level = 1;
            MaxSpeed = 245;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.7;
            Unpurchasable = true
        };
        ["Coral Cruiser Boat"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1;
            Bobbing = 2.5;
            BobbingSpeed = 1;
            Description = "Fischer Special Special!";
            Icon = "rbxassetid://71002238163754";
            Level = 0;
            MaxSpeed = 85;
            ObtainText = "Obtain on Starter Pack";
            Price = -1;
            StopEfficiency = 1.3;
            TurningSpeed = 0.5;
            Unpurchasable = true
        };
        Crab = {
            Accel = 5;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "quite the big crab...";
            Icon = "rbxassetid://126771105635898";
            Level = 1;
            MaxSpeed = 100;
            Price = -1;
            StopEfficiency = 3.5;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Crimson Jetski"] = {
            Accel = 0.35;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Speeding on the crimson currents...";
            Icon = "rbxassetid://73133558403581";
            Level = 1;
            MaxSpeed = 190;
            Price = -1;
            StopEfficiency = 3.5;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Cthulhu Boat"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Extremely fast, and equally cursed...";
            Icon = "rbxassetid://95194471402955";
            Level = 1;
            MaxSpeed = 265;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 0.9;
            Unpurchasable = true
        };
        ["Cthulu's Cranium"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "What else is cooler than surfing the waves in the dreamers head?";
            Icon = "rbxassetid://70671327958329";
            Level = 1;
            MaxSpeed = 140;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 0.45;
            Unpurchasable = true
        };
        Cthulunaut = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "The Cthulunaut is a deep-sea submarine, glowing eerie green, its hull carved with eldritch patterns, gliding through the abyss like a cosmic nightmare..";
            Icon = "rbxassetid://87034267614710";
            IsSubmarine = true;
            Level = 70;
            MaxSpeed = 180;
            Price = -1;
            StopEfficiency = 3.5;
            SubmarineTier = "Deep";
            TurningSpeed = 0.7;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Cuddly Claw"] = {
            Accel = 1.55;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "Sail away in a floating claw machine, brimming with cuddly plushies just waiting to be won!";
            Icon = "rbxassetid://90334984370780";
            Level = 1;
            MaxSpeed = 235;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Curse III"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "The third in a line of vessels never meant to survive, Curse III is a razor-fast nightmare—armored in scorched plating, pulsing with unstable energy, and tuned to outrun whatever follows.";
            FakePrice = 4999;
            Icon = "rbxassetid://90591412447366";
            Level = 1;
            LimitedAmount = 10000;
            MaxSpeed = 255;
            Price = -1;
            ProductId = 3250004378;
            StopEfficiency = 1.75;
            TurningSpeed = 0.9;
            Unpurchasable = true
        };
        ["Curse IV"] = {
            Accel = 0.85;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Forged in the shadow of its predecessor, Curse IV is a spectral blur of menace and velocity-clad in jagged, void-kissed armor, thrumming with a volatile pulse that defies containment, built to slip through the jaws of fate itself.";
            FakePrice = 3799;
            Icon = "rbxassetid://83529303349813";
            Level = 1;
            LimitedAmount = 1000;
            MaxSpeed = 265;
            Price = -1;
            ProductId = 3338757372;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Cursed Banner Ship"] = {
            Accel = 0.35;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Sail in eerie style with the Cursed Banner — a sleek, dark ship glowing with haunting blue runes. Perfect for those who command the seas with a touch of mystery.";
            Icon = "rbxassetid://108455660194348";
            Level = 1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 1.8;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Cursed Rider"] = {
            Accel = 0.7;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "";
            Icon = "rbxassetid://127115059814209";
            Level = 900;
            MaxSpeed = 200;
            Price = 2000000;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Untradeable = true
        };
        ["Cursed Rowboat"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1.1;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "Row boat Small, cracked black wood with glowing blue runes. Oars twitch slightly. Surrounded by faint whispers.";
            Icon = "rbxassetid://106746141538836";
            Level = 1;
            MaxSpeed = 155;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Dead Fish Express"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "A haunting skeletal vessel shaped like the remains of a giant fish, its hollow bones creaking as it drifts through the waters.";
            Icon = "rbxassetid://96513560079594";
            Level = 1;
            MaxSpeed = 190;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.4;
            Unpurchasable = true
        };
        Demonwake = {
            Accel = 0.9;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Its wake trails with silent screams, swallowed by the sea before they're heard...";
            FakePrice = 3599;
            Icon = "rbxassetid://81319792737758";
            Level = 1;
            LimitedAmount = 1500;
            MaxSpeed = 265;
            Price = -1;
            ProductId = 3363580606;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Desolate Dragon"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1.2;
            Bobbing = 2.2;
            BobbingSpeed = 1;
            Description = "Ride on the almighty fury of the Desolate Dragon.";
            FakePrice = 4999;
            Icon = "rbxassetid://117449588157233";
            Level = 1;
            LimitedAmount = 25000;
            MaxSpeed = 230;
            Price = -1;
            ProductId = 3268963621;
            StopEfficiency = 1.8;
            TurningSpeed = 0.5;
            Unpurchasable = true
        };
        ["Dr. Glimmerfin's Boat"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.5;
            BobbingSpeed = 3;
            Description = "A research vessel typically piloted by a Dr. Glimmerfin, chasing secrets across the waves.";
            Icon = "rbxassetid://139332412278271";
            Level = 75;
            MaxSpeed = 100;
            Price = -1;
            StopEfficiency = 2.2;
            TurningSpeed = 0.33;
            Unpurchasable = true
        };
        Dreadcurrent = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 1;
            BobbingSpeed = 1;
            Description = "A titanic phantom adrift through mist and myth, its wails echo with the sorrow of sailors long swallowed by the deep.";
            Icon = "rbxassetid://116986982010060";
            Level = 1;
            MaxSpeed = 300;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.3;
            Unpurchasable = true
        };
        Dreadmarrow = {
            Accel = 0.85;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Dread forged from bone and bound in cursed chains, its fangs hunger for the abyss. Those who sail it are forever tethered to the dread that stirs beneath the waves...";
            FakePrice = 4099;
            Icon = "rbxassetid://120051046622713";
            Level = 1;
            LimitedAmount = 1650;
            MaxSpeed = 280;
            Price = -1;
            ProductId = 3388723099;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Dreamers Redemption"] = {
            Accel = 0.4;
            AlternateSpawn = 50;
            BackwardsEfficiency = 1;
            Bobbing = 1;
            BobbingSpeed = 1;
            Description = "A weathered vessel reborn from forgotten dreams, the Dreamer’s Redemption carries those who still believe the sea can forgive.";
            Icon = "rbxassetid://86672689180561";
            Level = 1;
            MaxSpeed = 235;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.5;
            Unpurchasable = true
        };
        Driftblub = {
            Accel = 0.4;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Blobbing...";
            Icon = "rbxassetid://120040570276125";
            Level = 1;
            MaxSpeed = 195;
            Price = -1;
            StopEfficiency = 3.5;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Dumbo = {
            Accel = 0.9;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "The most fearsome vessel with the face of a cuddle... Don’t let the eyes fool you, this ship bites back.";
            FakePrice = 4999;
            Icon = "rbxassetid://138237415970735";
            Level = 1;
            LimitedAmount = 25000;
            MaxSpeed = 245;
            Price = -1;
            ProductId = 3273792404;
            StopEfficiency = 1.5;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Dutchman's Spirit"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Only available during FischFright-2025";
            Icon = "rbxassetid://75246740836510";
            Level = 1;
            MaxSpeed = 220;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Easter Basket"] = {
            Accel = 0.35;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Ride through Easter in style!";
            Icon = "rbxassetid://125990379782355";
            Level = 1;
            MaxSpeed = 190;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Elite Chair"] = {
            Accel = 0.4;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "🔴 - Only for da elite people.";
            Icon = "rbxassetid://0";
            Level = 1;
            MaxSpeed = 220;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 2;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Elysian Jolt"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "A blur of light and silence; seen too late, gone too soon.";
            FakePrice = 3199;
            Icon = "rbxassetid://105222654240996";
            Level = 1;
            LimitedAmount = 1200;
            MaxSpeed = 260;
            Price = -1;
            ProductId = 3330350469;
            StopEfficiency = 3.5;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Evangeline = {
            Accel = 0.9;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "The light hymn that guides the dawnlit sea...";
            FakePrice = 3899;
            Icon = "rbxassetid://97571176415524";
            Level = 1;
            LimitedAmount = 1500;
            MaxSpeed = 270;
            Price = -1;
            ProductId = 3379910474;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Evil Quacker"] = {
            Accel = 1;
            BackwardsEfficiency = 1;
            Bobbing = 4;
            BobbingSpeed = 0.5;
            Description = "EVIL!";
            Icon = "rbxassetid://129375255775643";
            Level = -1;
            MaxSpeed = 45;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Explorer Diving Boat"] = {
            Accel = 0.65;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "LEGO Explorer Diving Boat";
            Icon = "rbxassetid://104314152947635";
            Level = 32;
            MaxSpeed = 150;
            Price = 0;
            StopEfficiency = 3;
            TurningSpeed = 0.5
        };
        ["Fisch Jet"] = {
            Accel = 0.7;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "A sleek engine of momentum, built to tear through boundless waters!";
            Icon = "rbxassetid://75366341515770";
            Level = 1;
            MaxSpeed = 270;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Fischmas Jetski"] = {
            Accel = 0.35;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "The Fischmas Jetski!";
            Icon = "rbxassetid://91906307864355";
            Level = 1;
            MaxSpeed = 220;
            Price = -1;
            StopEfficiency = 1.8;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Fischmas Speedboat"] = {
            Accel = 0.35;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "The Fischmas Speedboat!";
            Icon = "rbxassetid://130906482985374";
            Level = 1;
            MaxSpeed = 180;
            Price = -1;
            ProductId = 2677594734;
            StopEfficiency = 1.8;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Fish Bowl"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "A glass domed speed bowl that lets you ride the waves like you're in your own aquatic exhibit.";
            Icon = "rbxassetid://120431486261915";
            Level = 1;
            MaxSpeed = 240;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Fishing Boat"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1.5;
            Description = "A trusty boat to reel in even the biggest fish!";
            Icon = "rbxassetid://76012409822158";
            Level = 25;
            MaxSpeed = 75;
            Price = 20000;
            StopEfficiency = 2;
            TurningSpeed = 0.5
        };
        ["Fishscale Waverider"] = {
            Accel = 0.4;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Insane waverider!!";
            ExpirationDate = "1737817200000";
            Icon = "rbxassetid://72839527239663";
            Level = 1;
            LimitedAmount = 10000;
            MaxSpeed = 230;
            Price = -1;
            ProductId = 2701903593;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Flipper Express"] = {
            Accel = 0.4;
            AlternateSpawn = 50;
            BackwardsEfficiency = 1;
            Bobbing = 1;
            BobbingSpeed = 1;
            Description = "The ultimate whale-inspired luxury yacht! With a sleek, fin-like design and a powerful tail-shaped stern, it glides through the waves with effortless grace.";
            Icon = "rbxassetid://94391641146651";
            Level = 1;
            MaxSpeed = 245;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.3;
            Unpurchasable = true
        };
        ["Flying Dutchman"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 6;
            BobbingSpeed = 3;
            Description = "Only available during FischFright-2024";
            Icon = "rbxassetid://86518345531497";
            Level = 0;
            MaxSpeed = 80;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.3;
            Unpurchasable = true
        };
        Ghosdeeri = {
            Accel = 0.3;
            BackwardsEfficiency = 3;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Halloween Spotlight Reward [Key Tier]";
            Icon = "rbxassetid://135512597871946";
            Level = 1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.2;
            Unpurchasable = true
        };
        ["Ghosts Pirate Ship"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1;
            Bobbing = 6;
            BobbingSpeed = 3;
            Description = "Silent, deadly, cursed forever. [Ghosts faction max rank vessel]";
            HideInShop = true;
            Icon = "rbxassetid://84575570131047";
            Level = 1;
            MaxSpeed = 320;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.3;
            Unpurchasable = true
        };
        Gondola = {
            Accel = 0.4;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "HOW CAN A GONDOLA GO THIS FAST??";
            Icon = "rbxassetid://86464358166303";
            Level = 1;
            MaxSpeed = 230;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        Gravedigger = {
            Accel = 0.99;
            BackwardsEfficiency = 1.3;
            Bobbing = 2;
            BobbingSpeed = 2;
            Description = "A sinister jetski that rips through the waves like a wraith, leaving a chilling wake under the moon's ghostly glow...";
            FakePrice = 4099;
            Icon = "rbxassetid://76700259048420";
            Level = 1;
            LimitedAmount = 12000;
            MaxSpeed = 287;
            Price = -1;
            ProductId = 3439887277;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Gravy Boat"] = {
            Accel = 0.3;
            BackwardsEfficiency = 3;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Don't fall in!";
            Icon = "rbxassetid://126143433396617";
            Level = 1;
            MaxSpeed = 190;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.2;
            Unpurchasable = true
        };
        ["Guardian of Atlantis"] = {
            Accel = 0.4;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "The Guardian of Atlantis Boat is a majestic vessel with glowing runes and a carved guardian’s visage, gliding through waves with regal power.";
            Icon = "rbxassetid://127484673570168";
            Level = 1;
            MaxSpeed = 240;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.25;
            Unpurchasable = true
        };
        ["Head Of Cthulu"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A seaborne vessel shaped like Cthulhu's head.";
            Icon = "rbxassetid://90849707354349";
            Level = 1;
            MaxSpeed = 135;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 0.45;
            Unpurchasable = true
        };
        ["Holiday Steampunk Ship"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.5;
            BobbingSpeed = 3;
            Description = "Holiday Steampunk Ship";
            Icon = "rbxassetid://90047369440873";
            Level = 1;
            MaxSpeed = 100;
            Price = -1;
            ProductId = 2677594586;
            StopEfficiency = 2.2;
            TurningSpeed = 0.33;
            Unpurchasable = true
        };
        ["Holiday Themed - Speedboat"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Sail around at unpresedented speeds! HOLIDAY XMAS!";
            Icon = "rbxassetid://75366616883373";
            Level = 1;
            MaxSpeed = 150;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 0.54;
            Unpurchasable = true
        };
        ["Hollywave Cruiser"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 1;
            BobbingSpeed = 1;
            Description = "Santa's Luxury Christmas ride!";
            ExpirationDate = "1736607600000";
            Icon = "rbxassetid://98034431985434";
            Level = 1;
            LimitedAmount = 10000;
            MaxSpeed = 230;
            Price = -1;
            ProductId = 2680232259;
            StopEfficiency = 2;
            TurningSpeed = 0.3;
            Unpurchasable = true
        };
        ["Hourglass Boat"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1.1;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "A boat where time moves as fast as you do!";
            Icon = "rbxassetid://71270478813335";
            Level = 1;
            MaxSpeed = 165;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        Hovercraft = {
            Accel = 0.22;
            BackwardsEfficiency = 1;
            Bobbing = 1;
            BobbingSpeed = 1;
            Description = "Hover around the seas! [Contribution by @DDkreep, @LiamGame09 and @kylecat11]";
            Icon = "rbxassetid://86981907121786";
            Level = 15;
            MaxSpeed = 55;
            Price = 7000;
            StopEfficiency = 0.7;
            TurningSpeed = 0.4
        };
        Hoverslime = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "This is a futuristic slime boat! covered in dripping neon-green slime.";
            FakePrice = 1499;
            Icon = "rbxassetid://106516837415800";
            Level = 1;
            LimitedAmount = 20000;
            MaxSpeed = 180;
            Price = -1;
            ProductId = 3311964710;
            StopEfficiency = 3.5;
            TurningSpeed = 0.7;
            Unpurchasable = true
        };
        ["Huge Utility Boat"] = {
            Accel = 0.35;
            AlternateSpawn = 30;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A massive vessel built for pure strength, it handles major hauling tasks.";
            Icon = "rbxassetid://99089060153627";
            IsUtility = true;
            Level = 1;
            MaxSpeed = 190;
            Price = 1500000;
            StopEfficiency = 2;
            TurningSpeed = 0.8;
            Unpurchasable = false;
            Untradeable = true;
            UtilityTier = 4
        };
        ["Inky Pal"] = {
            Accel = 0.7;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "Bobbing cheerfully on the waves, this playful squid leaves behind a trail of bubbly ink and endless joy!";
            Icon = "rbxassetid://90969307755830";
            Level = 1;
            MaxSpeed = 245;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Irish Jig"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.5;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "A lively vessel that dances upon the waves like a true Celtic tune! The Irish Jig is a vibrant and sturdy boat, built for both adventure and celebration.";
            Icon = "rbxassetid://93666916290774";
            Level = 1;
            MaxSpeed = 228;
            Price = -1;
            StopEfficiency = 1.4;
            TurningSpeed = 0.7;
            Unpurchasable = true
        };
        Ivorous = {
            Accel = 1.11;
            BackwardsEfficiency = 1.3;
            Bobbing = 2;
            BobbingSpeed = 2;
            Description = "Delicate petals lining the waves before you; its elegant lilac gradient allowing any journey to be all the more gorgeous...";
            FakePrice = 4099;
            Icon = "rbxassetid://118984110095434";
            Level = 1;
            LimitedAmount = 7500;
            MaxSpeed = 293;
            Price = -1;
            ProductId = 3456277974;
            StopEfficiency = 1.75;
            TurningSpeed = 1.25;
            Unpurchasable = true
        };
        Jetski = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Ski around with a friend at insane speeds!";
            Icon = "rbxassetid://129451187335290";
            Level = 60;
            MaxSpeed = 180;
            Price = 50000;
            StopEfficiency = 3.5;
            TurningSpeed = 0.7
        };
        ["Jungle Explorer Boat"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1;
            Bobbing = 0;
            BobbingSpeed = 0;
            Description = "May prove to be useful for the Lost Jungle...";
            Icon = "rbxassetid://112252823794589";
            Level = 1;
            MaxSpeed = 210;
            Price = -1;
            StopEfficiency = 0.01;
            TurningSpeed = 0.5;
            Unpurchasable = true
        };
        ["King of the Kraken"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A small, standing ship with a sleek black hull and glowing blue accents, the fastest vessel in the game.";
            Icon = "rbxassetid://91329391188038";
            Level = 1;
            MaxSpeed = 260;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 0.9;
            Unpurchasable = true;
            Untradeable = true
        };
        ["King’s Throne"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "A royal vessel, fit for a King!";
            Icon = "rbxassetid://127922702096875";
            Level = 1;
            MaxSpeed = 230;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Kraken of the Void"] = {
            Accel = 0.9;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A cosmic leviathan draped in shadow and silence, it rends reality itself with every rise from the fathomless dark. Once a sovereign; now a void-corrupted echo of a throne long drowned.";
            FakePrice = 3599;
            Icon = "rbxassetid://110936424777607";
            Level = 1;
            LimitedAmount = 1500;
            MaxSpeed = 260;
            Price = -1;
            ProductId = 3346989166;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Large Utility Boat"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Highly strong and capable, built for heavy-duty tasks.";
            Icon = "rbxassetid://83785780610841";
            IsUtility = true;
            Level = 1;
            MaxSpeed = 150;
            Price = 500000;
            StopEfficiency = 2;
            TurningSpeed = 0.8;
            Unpurchasable = false;
            Untradeable = true;
            UtilityTier = 3
        };
        ["Lion's Fury"] = {
            Accel = 0.7;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Lion’s Fury - Golden lion-shaped jetski. Fast, loud, and wild.";
            FakePrice = 4999;
            Icon = "rbxassetid://73233180943848";
            Level = 1;
            LimitedAmount = 15000;
            MaxSpeed = 235;
            Price = -1;
            ProductId = 3256916204;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Little Boo"] = {
            Accel = 1.55;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "Boo!";
            Icon = "rbxassetid://106522534076570";
            Level = 1;
            MaxSpeed = 245;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Loot Rider"] = {
            Accel = 0.35;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "The Loot Rider!";
            Icon = "rbxassetid://80827578890451";
            Level = 1;
            MaxSpeed = 190;
            Price = -1;
            StopEfficiency = 1.8;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Lotus Boat"] = {
            Accel = 1.1;
            BackwardsEfficiency = 1.1;
            Bobbing = 0.5;
            BobbingSpeed = 0.1;
            Description = "blooming along the waves..";
            Icon = "rbxassetid://95640290890526";
            Level = 1;
            MaxSpeed = 233;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 0.77;
            Unpurchasable = true
        };
        ["Love Crasher"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "What's better than spending your day on the beautiful Love Crasher?";
            FakePrice = 4999;
            Icon = "rbxassetid://121237191241453";
            Level = 1;
            LimitedAmount = 8000;
            MaxSpeed = 190;
            Price = -1;
            ProductId = 2837613240;
            StopEfficiency = 3.7;
            TurningSpeed = 0.35;
            Unpurchasable = true
        };
        ["Lucky Pot"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "Huh? I'm a lucky guy";
            Icon = "rbxassetid://122341403504224";
            Level = 1;
            MaxSpeed = 100;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Lucky Racer"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Feeling Lucky? Take this out for a spin...";
            FakePrice = 4999;
            Icon = "rbxassetid://103178311237682";
            Level = 1;
            LimitedAmount = 15000;
            MaxSpeed = 235;
            Price = -1;
            ProductId = 3238002239;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Luxury Speedboat"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Sail around at unprecedented speeds!";
            Icon = "rbxassetid://128624450327470";
            Level = 50;
            MaxSpeed = 150;
            Price = 20000;
            StopEfficiency = 1.5;
            TurningSpeed = 0.54
        };
        ["Macabre Mistress"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.3;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A sleek black phantom streaking across the water, leaving trails of pink fury in its wake. Born of midnight and menace, it rules the waves with deadly speed.";
            FakePrice = 4099;
            Icon = "rbxassetid://134759812744575";
            Level = 1;
            LimitedAmount = 15000;
            MaxSpeed = 285;
            Price = -1;
            ProductId = 3427566517;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Magnet = {
            Accel = 5;
            BackwardsEfficiency = 1;
            Bobbing = 0;
            BobbingSpeed = 0;
            Description = "Doesn't seem very effective for boating...";
            Icon = "rbxassetid://127635918006645";
            Level = 1;
            MaxSpeed = 10;
            Price = -1;
            StopEfficiency = 5;
            TurningSpeed = 1;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Marauder Ship"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 6;
            BobbingSpeed = 3;
            Description = "Fast, fierce, unstoppable. [Midas' Mates faction max rank vessel]";
            HideInShop = true;
            Icon = "rbxassetid://85241378337056";
            Level = 1;
            MaxSpeed = 250;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.25;
            Unpurchasable = true
        };
        ["Mecha Ray"] = {
            Accel = 0.78;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "The Mecha Ray tears through the ocean at blistering speed, its armored frame built for raw, unstoppable power. A predator of metal and momentum, nothing outpaces its strike...";
            FakePrice = 4099;
            Icon = "rbxassetid://84127727922563";
            Level = 1;
            LimitedAmount = 15000;
            MaxSpeed = 288;
            Price = -1;
            ProductId = 3421394004;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Medium Utility Boat"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A balanced and reliable vessel, designed for strenuous tasks and moderate work.";
            Icon = "rbxassetid://101438175950563";
            IsUtility = true;
            Level = 1;
            MaxSpeed = 110;
            Price = 250000;
            StopEfficiency = 2;
            TurningSpeed = 0.8;
            Unpurchasable = false;
            Untradeable = true;
            UtilityTier = 2
        };
        Meowmobile = {
            Accel = 1.5;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "An adorable, cuddly kitty balancing on a fluffy ball of yarn! Roll thru' the ocean while driving this kitty and her favorite toy!";
            Icon = "rbxassetid://106311545459291";
            Level = 1;
            MaxSpeed = 245;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Meteor = {
            Accel = 0.05;
            BackwardsEfficiency = 1;
            Bobbing = 0;
            BobbingSpeed = 0;
            Description = "💥";
            Icon = "rbxassetid://81699504594864";
            Level = 1;
            MaxSpeed = math.huge;
            Price = -1;
            StopEfficiency = 0.01;
            TurningSpeed = 0.5;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Midnight Cruiser"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Midnight Cruiser!";
            Icon = "rbxassetid://111198001071610";
            Level = 50;
            MaxSpeed = 150;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 0.54;
            Unpurchasable = true
        };
        Mila = {
            Accel = 0.65;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "🥝";
            Icon = "rbxassetid://73843249851684";
            Level = 1;
            MaxSpeed = 250;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 1;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Mini Crowned Anglerfish"] = {
            Accel = 3;
            BackwardsEfficiency = 1;
            Bobbing = 3;
            BobbingSpeed = 2;
            Description = "Small, yet still dangerous...";
            Icon = "rbxassetid://92377448534492";
            Level = 1;
            MaxSpeed = 140;
            Price = -1;
            StopEfficiency = 5;
            TurningSpeed = 1;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Mini Jetski"] = {
            Accel = 10;
            BackwardsEfficiency = 2;
            Bobbing = 0.1;
            BobbingSpeed = 0.01;
            Description = "it's a mystery how this can hold a person...";
            Icon = "rbxassetid://76036450232117";
            Level = 1;
            MaxSpeed = 180;
            Price = -1;
            StopEfficiency = 5;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Molten Jetski"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "A compact, agile watercraft built from obsidian and infused with the raw power of an erupting volcano.";
            Icon = "rbxassetid://95003767264216";
            Level = 1;
            MaxSpeed = 235;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        Mossjaw = {
            Accel = 0.2;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "You've tamed a Mossjaw!... How well does it ride?";
            Icon = "rbxassetid://129498791494514";
            Level = 1;
            MaxSpeed = 300;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Mosslurker = {
            Accel = 0.85;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 2;
            Description = "An ancient, moss-draped titan; now tamed for riding!";
            Icon = "rbxassetid://118394743462568";
            Level = 1;
            MaxSpeed = 250;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Mr. Thankful"] = {
            Accel = 1.12;
            BackwardsEfficiency = 1.1;
            Bobbing = 0.5;
            BobbingSpeed = 0.1;
            Description = "";
            Icon = "rbxassetid://96565898569609";
            Level = 1;
            MaxSpeed = 244;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 0.77;
            Unpurchasable = false
        };
        ["Mummy Puppy"] = {
            Accel = 1.2;
            BackwardsEfficiency = 1.1;
            Bobbing = 0.5;
            BobbingSpeed = 0.1;
            Description = "wrapped in cuteness!";
            Icon = "rbxassetid://94671599919126";
            Level = 1;
            MaxSpeed = 240;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 0.85;
            Unpurchasable = true
        };
        Nemesis = {
            Accel = 1.23;
            BackwardsEfficiency = 1.3;
            Bobbing = 2;
            BobbingSpeed = 2;
            Description = "A phantom predator born from abyssal steel, the Nemesis carves oceans into screaming ribbons of foam. Twin turbines howl like vengeful gods, propelling her hull through liquid night at speeds that blur horizon and heartbeat...";
            FakePrice = 4099;
            Icon = "rbxassetid://116416101709891";
            Level = 1;
            LimitedAmount = 11000;
            MaxSpeed = 285;
            Price = -1;
            ProductId = 3445698297;
            StopEfficiency = 1.75;
            TurningSpeed = 1.01;
            Unpurchasable = true
        };
        ["Nessie Nomad"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.5;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Ride this legendary beast wherever the currents calls!";
            Icon = "rbxassetid://79582771766209";
            Level = 1;
            MaxSpeed = 220;
            Price = -1;
            StopEfficiency = 3;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Nessie's Skeleton"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Woah... So spooky...";
            Icon = "rbxassetid://74134944858605";
            Level = 1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Nocturne = {
            Accel = 0.85;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "The dark whisper that stalks the midnight tide...";
            FakePrice = 4099;
            Icon = "rbxassetid://104260287643249";
            Level = 1;
            LimitedAmount = 1250;
            MaxSpeed = 275;
            Price = -1;
            ProductId = 3372328768;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Novaris = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A streamlined jetski forged of starlight and steel, its frame glimmers with shifting constellations as cosmic trails of neon blue and violet flare in its wake; riding it feels like carving straight through the fabric of the galaxy...";
            FakePrice = 4099;
            Icon = "rbxassetid://112973090688508";
            Level = 1;
            LimitedAmount = 7500;
            MaxSpeed = 285;
            Price = -1;
            ProductId = 3415384709;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Orange Unicycle"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "One wheeled orange beauty built for balance and undeniable style.";
            FakePrice = 1499;
            Icon = "rbxassetid://119550165521495";
            Level = 1;
            LimitedAmount = 20000;
            MaxSpeed = 180;
            Price = -1;
            ProductId = 3301481855;
            StopEfficiency = 3.5;
            TurningSpeed = 0.7;
            Unpurchasable = true
        };
        ["Orca Boat"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "The Orca Boat glides through the waves with sleek black-and-white patterns, mimicking the grace of a real life Orca.";
            Icon = "rbxassetid://123444755161419";
            Level = 1;
            MaxSpeed = 180;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.35;
            Unpurchasable = true
        };
        Pantheress = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Sleek but sturdy boat radiating in feline power, rendered in brilliant pink lights; slicing through the current swiftly...";
            FakePrice = 4099;
            Icon = "rbxassetid://72518039573703";
            Level = 1;
            LimitedAmount = 5000;
            MaxSpeed = 285;
            Price = -1;
            ProductId = 3408780955;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Pastel Impulse"] = {
            Accel = 0.9;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A vessel born of shifting light, painted in endless hues; it sails as though chasing the horizon’s eternal rainbow.";
            FakePrice = 3799;
            Icon = "rbxassetid://100395693600042";
            Level = 1;
            LimitedAmount = 1500;
            MaxSpeed = 275;
            Price = -1;
            ProductId = 3395832950;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Pirate Ship"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 6;
            BobbingSpeed = 3;
            Description = "Argggg Matey!!";
            Icon = "rbxassetid://88689922648864";
            Level = 30;
            MaxSpeed = 80;
            Price = 20000;
            StopEfficiency = 2;
            TurningSpeed = 0.3
        };
        Pontoon = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 1;
            BobbingSpeed = 1;
            Description = "Great for parties with some buddies!";
            Icon = "rbxassetid://126083630313652";
            Level = 30;
            MaxSpeed = 40;
            Price = 20000;
            StopEfficiency = 2;
            TurningSpeed = 0.4
        };
        ["Popsicle Jetski"] = {
            Accel = 0.7;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Cool off in style; this frosty ride turns every wave into a sweet escape.";
            FakePrice = 1999;
            Icon = "rbxassetid://131282114800723";
            Level = 1;
            LimitedAmount = 2500;
            MaxSpeed = 250;
            Price = -1;
            ProductId = 3324354033;
            StopEfficiency = 3.5;
            TurningSpeed = 0.95;
            Unpurchasable = true
        };
        ["Pride of Fisch"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 1;
            BobbingSpeed = 1;
            Description = "A majestic mega-yacht designed for true captains.";
            Icon = "rbxassetid://126957372936382";
            Level = 1;
            MaxSpeed = 230;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.3;
            Unpurchasable = true
        };
        Puffernaut = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Stuffed like a fishball and brave like a bean, this bloated beauty puffs its way where no bubble should go.";
            FakePrice = 4999;
            Icon = "rbxassetid://139108850838086";
            IsSubmarine = true;
            Level = 1;
            LimitedAmount = 20000;
            MaxSpeed = 200;
            Price = -1;
            ProductId = 3278181273;
            StopEfficiency = 3.5;
            SubmarineTier = "Deep";
            TurningSpeed = 0.7;
            Unpurchasable = true;
            Untradeable = true
        };
        Purrari = {
            Accel = 1;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "The Purrari; fast, playful, and full of personality!";
            Icon = "rbxassetid://117729503245185";
            Level = 1;
            MaxSpeed = 250;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Quack Cruiser"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 4;
            BobbingSpeed = 0.5;
            Description = "This duck sailed up to the lemonade stand.";
            Icon = "rbxassetid://110958729645045";
            Level = 35;
            MaxSpeed = 45;
            Price = 5000;
            StopEfficiency = 2;
            TurningSpeed = 0.5
        };
        ["Really Fast Jetski"] = {
            Accel = 2.95;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "🔴";
            Icon = "rbxassetid://130682434368049";
            Level = 1;
            MaxSpeed = 500;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 2.5;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Reborn Flying Dutchman"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 6;
            BobbingSpeed = 3;
            Description = "Only available during FischFright-2025";
            Icon = "rbxassetid://105501305851016";
            Level = 0;
            MaxSpeed = 250;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.3;
            Unpurchasable = true
        };
        ["Red Marlins Ship"] = {
            Accel = 0.15;
            BackwardsEfficiency = 1;
            Bobbing = 6;
            BobbingSpeed = 3;
            Description = "Red sails, no survivors. [Red Marlins faction max rank vessel]";
            HideInShop = true;
            Icon = "rbxassetid://91179825470447";
            Level = 1;
            MaxSpeed = 210;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.2;
            Unpurchasable = true
        };
        ["Red Racer"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "A luxurious speedboat built for thrill and elegance, combining elite craftsmanship with unmatched velocity on the water.";
            Icon = "rbxassetid://137758255643127";
            Level = 1;
            MaxSpeed = 225;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Reef Ripper"] = {
            Accel = 0.75;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Carve through vicious waves with razor-edged speed! Old markings crawl along its scarred frame, a testament to battles fought with the sea.";
            Icon = "rbxassetid://73264347167008";
            Level = 1;
            MaxSpeed = 215;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Reindeer Cruiser"] = {
            Accel = 0.25;
            BackwardsEfficiency = 1;
            Bobbing = 4;
            BobbingSpeed = 0.5;
            Description = "A ducky boat with a pretty convincing reindeer disguise. [Only obtainable during Fischmas 2024]";
            Icon = "rbxassetid://127716910078260";
            Level = 1;
            MaxSpeed = 55;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.5;
            Unpurchasable = true
        };
        ["Relic Jungle Explorer Boat"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 0;
            BobbingSpeed = 0;
            Description = "May prove to be useful for the Lost Jungle... A reward to those who solved the long forgotten Relic Rod puzzle!";
            Icon = "rbxassetid://133801886273194";
            Level = 1;
            MaxSpeed = 220;
            Price = -1;
            StopEfficiency = 0.01;
            TurningSpeed = 0.5;
            Unpurchasable = true
        };
        Riptide = {
            Accel = 1.33;
            BackwardsEfficiency = 1.3;
            Bobbing = 2;
            BobbingSpeed = 2;
            Description = "";
            FakePrice = 4099;
            Icon = "rbxassetid://113311825610773";
            Level = 1;
            LimitedAmount = 7500;
            MaxSpeed = 287;
            Price = -1;
            ProductId = 3450675526;
            StopEfficiency = 1.75;
            TurningSpeed = 1.1;
            Unpurchasable = true
        };
        ["Roasted Turkey"] = {
            Accel = 0.35;
            BackwardsEfficiency = 3;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Tasty! It got a little wet though...";
            Icon = "rbxassetid://122525178200973";
            Level = 1;
            MaxSpeed = 180;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.2;
            Unpurchasable = true
        };
        Rowboat = {
            Accel = 0.15;
            BackwardsEfficiency = 1;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "Sail the seas with your trusty paddles!";
            Icon = "rbxassetid://134432015160761";
            Level = 0.5;
            MaxSpeed = 25;
            Price = 400;
            StopEfficiency = 2;
            TurningSpeed = 0.4
        };
        ["S.S. Tuskhorn"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Carved elephant-head war boat. Heavy, ancient, unshakable.";
            Icon = "rbxassetid://117064100317202";
            Level = 1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.4;
            Unpurchasable = true
        };
        ["Sandslasher Boat"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A big scary worm thing.";
            Icon = "rbxassetid://107928250302719";
            Level = 1;
            MaxSpeed = 300;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Santa’s Jetski"] = {
            Accel = 0.4;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Santa’s Jetski christmas version!";
            Icon = "rbxassetid://140332102870016";
            Level = 1;
            MaxSpeed = 220;
            Price = -1;
            ProductId = 2677594486;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Scarlet Pirate Ship"] = {
            Accel = 0.1;
            BackwardsEfficiency = 1;
            Bobbing = 6;
            BobbingSpeed = 3;
            Description = "For true pirates...";
            Icon = "rbxassetid://89703250732386";
            Level = 1;
            MaxSpeed = 250;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.3;
            Unpurchasable = true
        };
        Scorpferno = {
            Accel = 1.35;
            BackwardsEfficiency = 1.3;
            Bobbing = 2;
            BobbingSpeed = 2;
            Description = "A boat engulfed in infernal flames, accompanies by a sharp, dagger-like stinger to protect you on your treacherous endeavors...";
            FakePrice = 4099;
            Icon = "rbxassetid://93892671133771";
            Level = 1;
            LimitedAmount = 7500;
            MaxSpeed = 295;
            Price = -1;
            ProductId = 3461672574;
            StopEfficiency = 1.75;
            TurningSpeed = 1.11;
            Unpurchasable = false
        };
        ["Sea Pegasus"] = {
            Accel = 0.35;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "The Sea Pegasus!";
            Icon = "rbxassetid://72935532824780";
            Level = 1;
            MaxSpeed = 180;
            Price = -1;
            StopEfficiency = 1.8;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Serpent Cruiser"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "The Serpent Cruiser is a sleek, snake-like vessel with glowing accents, built for speed and elegance as it weaves through any terrain.";
            Icon = "rbxassetid://139476969255100";
            Level = 1;
            MaxSpeed = 180;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.35;
            Unpurchasable = true
        };
        ["Sharkie Floatie"] = {
            Accel = 1.2;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "chomp!";
            Icon = "rbxassetid://104659968533700";
            Level = 1;
            MaxSpeed = 245;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Silent Speeder"] = {
            Accel = 0.9;
            BackwardsEfficiency = 1.5;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Cut through the waves with the Silent Speeder, a stealthy high-speed boat built for sleek escapes and smooth cruising.";
            FakePrice = 1499;
            Icon = "rbxassetid://119932849004727";
            Level = 1;
            LimitedAmount = 20000;
            MaxSpeed = 240;
            Price = -1;
            ProductId = 3287040610;
            StopEfficiency = 2;
            TurningSpeed = 0.9;
            Unpurchasable = true
        };
        ["Skygold Sprinter"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "A flash of sunlit speed, built to streak across the sea like lightning in daylight.";
            Icon = "rbxassetid://116876239112309";
            Level = 1;
            MaxSpeed = 240;
            Price = -1;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Sleepy Bear"] = {
            Accel = 1.55;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "Don't wake him!";
            Icon = "rbxassetid://127181966135463";
            Level = 1;
            MaxSpeed = 245;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Sleigh = {
            Accel = 0.4;
            BackwardsEfficiency = 0.85;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "Deliver presents at ridiculous speeds! [Only obtainable during Fischmas 2024]";
            Icon = "rbxassetid://113467920745327";
            Level = 1;
            MaxSpeed = 90;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["Small Utility Boat"] = {
            Accel = 0.15;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A lightweight utility boat, made for short trips and simple work.";
            Icon = "rbxassetid://108811112310028";
            IsUtility = true;
            Level = 1;
            MaxSpeed = 80;
            Price = 50000;
            StopEfficiency = 2;
            TurningSpeed = 0.8;
            Unpurchasable = false;
            Untradeable = true;
            UtilityTier = 1
        };
        ["Smurf Boat"] = {
            Accel = 0.5;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "The Official Smurf Boat!";
            HideInShop = true;
            Icon = "rbxassetid://107978832723436";
            Level = 1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 3.5;
            TurningSpeed = 0.7;
            Unpurchasable = true
        };
        ["Snowmobile Jetski"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Jetski frozen christmas version!";
            Icon = "rbxassetid://132722267987667";
            Level = 60;
            MaxSpeed = 200;
            ObtainText = "Obtain on Christmas Bundle";
            Price = -1;
            StopEfficiency = 3.5;
            TurningSpeed = 0.7;
            Unpurchasable = true
        };
        Speedboat = {
            Accel = 0.25;
            BackwardsEfficiency = 1;
            Bobbing = 2.5;
            BobbingSpeed = 1;
            Description = "Sail around at remarkable speeds!";
            Icon = "rbxassetid://130743409246855";
            Level = 20;
            MaxSpeed = 85;
            Price = 15000;
            StopEfficiency = 1.3;
            TurningSpeed = 0.5
        };
        ["Stinky Gurt"] = {
            Accel = 6.7;
            BackwardsEfficiency = 67;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "pee yew!";
            Icon = "rbxassetid://134432015160761";
            Level = 1;
            MaxSpeed = 300;
            Price = -1;
            StopEfficiency = 67;
            TurningSpeed = 1.67;
            Unpurchasable = true;
            Untradeable = true
        };
        Submarine = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "A submarine, typically used for entering only the deepest of trenches.";
            Icon = "rbxassetid://94549000992556";
            IsSubmarine = true;
            Level = 70;
            MaxSpeed = 180;
            Price = 1500000;
            StopEfficiency = 3.5;
            TurningSpeed = 0.7;
            Untradeable = true
        };
        Sunflower = {
            Accel = 1.7;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "Perfect for pollinating!";
            Icon = "rbxassetid://132322372104462";
            Level = 1;
            MaxSpeed = 240;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Sunny Ducky"] = {
            Accel = 1.75;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "A chill duck floatie boat rocking beach shades, perfect for cruising sunny waves in style!";
            Icon = "rbxassetid://127740682057615";
            Level = 1;
            MaxSpeed = 225;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        Surfboard = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 3;
            BobbingSpeed = 0.5;
            Description = "Surf the waves, catch the sharks!";
            Icon = "rbxassetid://140475994837078";
            Level = 7;
            MaxSpeed = 30;
            Price = 1500;
            StopEfficiency = 2;
            TurningSpeed = 0.5
        };
        ["Sushi-Rider"] = {
            Accel = 1.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "Ride the waves on a wasabi-fueled jetstream with the Sushi-Rider; fresh, fast, and dangerously delicious.";
            Icon = "rbxassetid://109283579319074";
            Level = 1;
            MaxSpeed = 230;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Swan Boat"] = {
            Accel = 0.35;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "The Swan Boat!";
            Icon = "rbxassetid://72911569404830";
            Level = 1;
            MaxSpeed = 180;
            Price = -1;
            StopEfficiency = 1.8;
            TurningSpeed = 0.6;
            Unpurchasable = true
        };
        ["The Blubbernaut"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "A compact, heavy-duty whale themed submarine with a reinforced shell and powerful thrusters, built for deep-sea dominance.";
            Icon = "rbxassetid://132147167716037";
            IsSubmarine = true;
            Level = 70;
            MaxSpeed = 180;
            Price = -1;
            StopEfficiency = 3.5;
            SubmarineTier = "Deep";
            TurningSpeed = 0.7;
            Unpurchasable = true;
            Untradeable = true
        };
        ["The Brick Hatchboat"] = {
            Accel = 6.7;
            BackwardsEfficiency = 1.1;
            Bobbing = 1;
            BobbingSpeed = 0.3;
            Description = "SUPER REAL.";
            Icon = "rbxassetid://75184886925945";
            Level = 1;
            MaxSpeed = 1500;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 1;
            Unpurchasable = true;
            Untradeable = true
        };
        ["The Essex Boat"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "Crafted for thrilling adventures, this Jurassic World-themed boat is built for exploring untamed waters with a prehistoric edge.";
            HideInShop = true;
            Icon = "rbxassetid://98242807552885";
            Level = 1;
            MaxSpeed = 250;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.54;
            Unpurchasable = true
        };
        ["The Mawrider"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "Deep-sea vessel inspired by the elusive anglerfish.";
            FakePrice = 4999;
            Icon = "rbxassetid://134058280576237";
            Level = 1;
            LimitedAmount = 5000;
            MaxSpeed = 230;
            Price = -1;
            ProductId = 3221390711;
            StopEfficiency = 3.7;
            TurningSpeed = 0.65;
            Unpurchasable = true
        };
        ["The Pearl"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 6;
            BobbingSpeed = 3;
            Description = "No one knows what sails this ship...";
            Icon = "rbxassetid://140297535873347";
            Level = 90;
            MaxSpeed = 95;
            Price = 50000;
            StopEfficiency = 3;
            TurningSpeed = 0.3
        };
        Theo = {
            Accel = 0.65;
            BackwardsEfficiency = 1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "plutoly forced me to do this - kiwi";
            Icon = "rbxassetid://114616291594414";
            Level = 1;
            MaxSpeed = 250;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 1;
            Unpurchasable = true;
            Untradeable = true
        };
        Titan = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "Huh? Who would want this?";
            Icon = "rbxassetid://124154643224531";
            Level = 40;
            MaxSpeed = 45;
            Price = 5000;
            StopEfficiency = 1.5;
            TurningSpeed = 0.2
        };
        ["Toro Veloce"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "A sleek, high-speed sports jetski with cutting-edge design—ride the waves like a champion!";
            FakePrice = 4999;
            Icon = "rbxassetid://134110214330233";
            Level = 1;
            LimitedAmount = 15000;
            MaxSpeed = 240;
            Price = -1;
            ProductId = 3231808129;
            StopEfficiency = 3.7;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        Towboat = {
            Accel = 0.67;
            BackwardsEfficiency = 67;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "Sail the seas with your trusty paddles!";
            Icon = "rbxassetid://134432015160761";
            Level = 1;
            MaxSpeed = 676.7;
            Price = -1;
            StopEfficiency = 67;
            TurningSpeed = 1.67;
            Unpurchasable = true;
            Untradeable = true
        };
        ["Tri-Brick Rider"] = {
            Accel = 1;
            BackwardsEfficiency = 1.1;
            Bobbing = 1.5;
            BobbingSpeed = 1;
            Description = "A sleek, triple thrust vessel built for rapid waveskimming, perfect for chasing the next big catch.";
            FakePrice = 1499;
            Icon = "rbxassetid://111237769377148";
            Level = 1;
            LimitedAmount = 40000;
            MaxSpeed = 230;
            Price = -1;
            ProductId = 3291165284;
            StopEfficiency = 1.5;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Vintage Hatchboat"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.3;
            Bobbing = 3;
            BobbingSpeed = 0.3;
            Description = "A classic sea cruiser with classy charm and retro flair, built for big ballers and big hauls.";
            Icon = "rbxassetid://92775381082833";
            Level = 1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 3.5;
            TurningSpeed = 0.3;
            Unpurchasable = true
        };
        ["Violet Viper"] = {
            Accel = 0.85;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "A razor-fast cyber boat wrapped in violet light; strikes the waves with deadly speed...";
            FakePrice = 4099;
            Icon = "rbxassetid://140470980522712";
            Level = 1;
            LimitedAmount = 2000;
            MaxSpeed = 280;
            Price = -1;
            ProductId = 3402362897;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Volcanic Research Boat"] = {
            Accel = 0.3;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "Dr. Finneus's Volcanic Research Quest Boat!";
            Icon = "rbxassetid://116581949935250";
            Level = 1;
            MaxSpeed = 135;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 0.45;
            Unpurchasable = true
        };
        ["Volcanic Speedboat"] = {
            Accel = 0.6;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.4;
            Description = "A fiery, high-speed vessel forged from volcanic rock and molten metal. Its sleek, ember-lined hull cuts through the water, leaving a trail of steam and glowing lava streaks in its wake.";
            FakePrice = 4999;
            Icon = "rbxassetid://86384399025640";
            Level = 1;
            LimitedAmount = 5000;
            MaxSpeed = 210;
            Price = -1;
            ProductId = 2954379627;
            StopEfficiency = 3.7;
            TurningSpeed = 0.35;
            Unpurchasable = true
        };
        Waffle = {
            Accel = 1.2;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 0.1;
            Description = "yummy!";
            Icon = "rbxassetid://140412578953176";
            Level = 1;
            MaxSpeed = 245;
            Price = -1;
            StopEfficiency = 4;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Warp Star"] = {
            Accel = 1;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "⭐";
            Icon = "rbxassetid://109247021565454";
            Level = 1;
            MaxSpeed = 200;
            Price = -1;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Whale Shark"] = {
            Accel = 0.1;
            BackwardsEfficiency = 1;
            Bobbing = 0;
            BobbingSpeed = 0;
            Description = "MY FAVORITE!";
            Icon = "rbxassetid://123258075251559";
            Level = 1;
            MaxSpeed = 500;
            Price = -1;
            StopEfficiency = 1;
            TurningSpeed = 1;
            Unpurchasable = true;
            Untradeable = true
        };
        Whaleski = {
            Accel = 0.9;
            BackwardsEfficiency = 1.1;
            Bobbing = 2;
            BobbingSpeed = 1;
            Description = "What’s faster than a whale in the ocean? Ride your Whaleski and fly right past your friends!";
            Icon = "rbxassetid://97509675338919";
            Level = 1;
            MaxSpeed = 245;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 0.8;
            Unpurchasable = true
        };
        ["Widow's Veil"] = {
            Accel = 0.8;
            BackwardsEfficiency = 1.3;
            Bobbing = 2;
            BobbingSpeed = 2;
            Description = "A scary, venomous vessel that strikes with silent precision; the Widow's Veil weaves death across the waves...";
            FakePrice = 4099;
            Icon = "rbxassetid://132654777972155";
            Level = 1;
            LimitedAmount = 12500;
            MaxSpeed = 290;
            Price = -1;
            ProductId = 3433641400;
            StopEfficiency = 1.75;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["Windsurfer Boast"] = {
            Accel = 0.65;
            BackwardsEfficiency = 1.1;
            Bobbing = 2.85;
            BobbingSpeed = 2;
            Description = "";
            Icon = "rbxassetid://75258416199056";
            Level = 800;
            MaxSpeed = 190;
            Price = 1000000;
            StopEfficiency = 1.75;
            TurningSpeed = 0.65;
            Untradeable = true
        };
        ["Witch's Broom"] = {
            Accel = 0.5;
            BackwardsEfficiency = 1;
            Bobbing = 3;
            BobbingSpeed = 0.5;
            Description = "Only available during FischFright-2025 [Can fly]";
            FlyingBoat = true;
            Icon = "rbxassetid://106471847970260";
            Level = 1;
            MaxHeight = 5000;
            MaxSpeed = 50;
            Price = -1;
            StopEfficiency = 2;
            TurningSpeed = 0.5;
            Unpurchasable = true;
            VerticalAccel = 0.5;
            VerticalMaxSpeed = 10;
            VerticalStopEfficiency = 2
        };
        ["Witch's Pot"] = {
            Accel = 0.2;
            BackwardsEfficiency = 1;
            Bobbing = 3;
            BobbingSpeed = 1;
            Description = "Only available during FischFright-2025";
            Icon = "rbxassetid://105798620146975";
            Level = 0;
            MaxSpeed = 145;
            Price = -1;
            StopEfficiency = 1.5;
            TurningSpeed = 1;
            Unpurchasable = true
        };
        ["ziggurat of dominance"] = {
            Accel = 10000000000000;
            BackwardsEfficiency = 1;
            Bobbing = 0;
            BobbingSpeed = 0;
            Description = "tarnished stinks";
            Icon = "rbxassetid://79567999104662";
            Level = 1;
            MaxSpeed = 10000000000000;
            Price = -1;
            StopEfficiency = 10000000000000;
            TurningSpeed = 0;
            Unpurchasable = true;
            Untradeable = true
        };
    };

    -- Системные поля
    Give = "function: 0xd68caecdc1b9dd64";
    Has = "function: 0x7352ea052ccdd4c4";
    HasSubmarine = "function: 0xba30d9a0153c9164";
    OnBoatProductPurchase = "function: 0x68dec011dca03314";
    Spawn = "function: 0x08f8cf0bd372e7e4";
    Ungive = "function: 0x8112edac1283d8b4";
}

return module
-- Module: vessels
-- Total items: 1
-- System fields: 0
